config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  root "calendars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
require 'open-uri'

class CalendarsController < ApplicationController
  before_action :set_calendar, only: %i[ show edit update destroy ]

  # GET /calendars or /calendars.json
  def index
    url = 'https://churchofjesuschrist.org/church-calendar/services/lucrs/ical/group/b03afe3544134ca59a839688d454fb2b'
    
    begin
      raw_file = URI.parse(url).read
      calendar = Calendar.create_or_find_by(url: url)
      calendar.update(raw: raw_file)
    rescue OpenURI::HTTPError => e
      logger.debug e
      raw_file = Calendar.find_by(url: url).raw
    end

    ical = Icalendar::Calendar.parse(raw_file).first

    events_by_month = ical.events.reverse.inject({}) do |by_month, event|
      month = DateTime::MONTHNAMES[event.dtstart.to_datetime.month]
      by_month[month] ? by_month[month] << event : by_month[month] = [event]
      by_month
    end

    @icalendar = OpenStruct.new(
      events: ical.events,
      events_by_month: events_by_month
    )
  end

  # GET /calendars/1 or /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars or /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: "Calendar was successfully created." }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1 or /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: "Calendar was successfully updated." }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1 or /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: "Calendar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calendar_params
      params.fetch(:calendar, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_calendar.html.erb
<div id="<%= dom_id calendar %>" class="scaffold_record">
  <p>
    <%= link_to "Show this calendar", calendar %>
  </p>
</div>

app/views/calendars/_form.html.erb
<%= form_with(model: calendar) do |form| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
        <% calendar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render "form", calendar: @calendar %>

<br>

<div>
  <%= link_to "Show this calendar", @calendar %> |
  <%= link_to "Back to calendars", calendars_path %>
</div>

app/views/calendars/index.html.erb
<div class="event-schedule-area-two bg-color pad100">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-title text-center">
          <div class="title-text">
            <h2>Raleigh South Stake Event Schedule</h2>
          </div>
          <p>
          Some explanation text
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 tab-content">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Month</th>
                <th scope="col">Day</th>
                <th scope="col">Time</th>
                <th scope="col">Description</th>
                <th class="text-center" scope="col">Location</th>
              </tr>
            </thead>
            <tbody>
              <% @icalendar.events_by_month.each do |month, events| %>
                <% events.each_with_index do |event, index| %>
                  <tr class="inner-box">
                    <th scope="row">
                      <h4>
                        <span><%= index.zero? ? month : nil %></span>
                      </h4>
                    </th>
                    <th scope="row">
                      <span><%= event.dtstart.to_datetime.strftime('%A / %d') %></span>
                    </th>
                    <td>
                      <span><%= event.dtstart.to_datetime.strftime('%l:%M %p') %></span>
                    </td>
                    <td>
                      <div class="event-wrap">
                        <h4><%= event.summary %></h4>
                        <div class='meta'>
                          <%= event.description %>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class="r-no">
                        <span><%= event.location ? event.location : nil %></span>
                      </div>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render "form", calendar: @calendar %>

<br>

<div>
  <%= link_to "Back to calendars", calendars_path %>
</div>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @calendar %>

<div>
  <%= link_to "Edit this calendar", edit_calendar_path(@calendar) %> |
  <%= link_to "Back to calendars", calendars_path %>

  <%= button_to "Destroy this calendar", calendar_path(@calendar), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>